### ISSUE TITLE
Error loading mod in 1.5.17 with Ultimate Belt

### ISSUE THREAD

**Issue by Senth** [mspielberg/factorio-miniloader#10]
After updating the mod to 1.5.17 I got this error.

`Failed to load mods: __miniloader__/data-updates.lua:12: attempt to index local 'loader' (a nil value)`

I'm using Ultimate Belts, if I disable Ultimate Belts the game and miniloader loads.

**Comment by mspielberg** [comment]
Should be fixed in 1.5.18. Thanks for the report!
