### ISSUE TITLE
Placed by blueprint (handly) filter loaders use only one(right) side of the belt.

### ISSUE THREAD

**Issue by AlxrMironovOldAcc** [mspielberg/factorio-miniloader#11]

**Comment by mspielberg** [comment]
I cannot reproduce your issue using standard vanilla construction bots. What is handly? I cannot find a mod by that name on the Factorio mod portal.

**Comment by AlxrMironovOldAcc** [comment]
Use blueprint for shadowing 4 filter loaders with 4 filter settings (i am use diferent Bobs ores, 4 filter options per loader).
Then place it handly (with Q and LCLK), loaders will placed correctly, but will use only 1 side of the belt.

**Comment by mspielberg** [comment]
I see. So you place a ghost by clicking with a blueprint, and then click on top of the ghost with a miniloader? That should be easy to fix. Thanks for the report!

(BTW, I think the English phrase you may be looking for is "by hand" or "manually.")

**Comment by mspielberg** [comment]
Fixed in v1.5.22
