### ISSUE TITLE
Miniloaders have less graphic priority and displayed behind (under) buildings. 

### ISSUE THREAD

**Issue by AlxrMironovOldAcc** [mspielberg/factorio-miniloader#13]

**Comment by mspielberg** [comment]
Belt structures (loaders, belts, underground belts) always render as the `transport-belt` priority and cannot be changed. The easiest fix would be to change the graphics themselves to fit entirely inside a 32x32 pixel tile.

**Comment by mspielberg** [comment]
Fixed in 1.6.0
