### ISSUE TITLE
Attempt to place loader between two belts, will invert it.

### ISSUE THREAD

**Issue by AlxrMironovOldAcc** [mspielberg/factorio-miniloader#14]
When you try to place loader between bottom and upper belt, for example drain side to bottom, flow side to top, loader will be placed drain side to top, flow side to bottom.

https://imgur.com/a/MCuIbLq

**Comment by mspielberg** [comment]
This is loader snapping in action. You can turn it off in options if it's not behaving the way you want. Placement between two belts is not a very common use.
