### ISSUE TITLE
Miniloaders server crash

### ISSUE THREAD

**Issue by ChurchOrganist** [mspielberg/factorio-miniloader#15]
Hi,

My i-craft.de server crashed over night with the following error.........
`304588.295 Error MainLoop.cpp:1035: Exception at tick 147111319: Error while running event miniloader::on_put_item (ID 9)
__miniloader__/lualib/blueprint.lua:93: attempt to index local 'stack' (a nil value)
304588.295 Error ServerMultiplayerManager.cpp:96: MultiplayerManager failed: "Error while running event miniloader::on_put_item (ID 9)
__miniloader__/lualib/blueprint.lua:93: attempt to index local 'stack' (a nil value)"
304588.295 Info ServerMultiplayerManager.cpp:699: mapTick(147111319) changing state from(InGame) to(Failed)`
Not sure why - another player was on the server at the time.

**Comment by mspielberg** [comment]
It looks like some other mod raised the on_put_item event (which happens when a player clicks with some item in their cursor) when the cursor was actually empty. That's not possible in vanilla, so it's probably some other misbehaving mod. IIRC Bluebuild can sometimes do this. I can add a workaround in Miniloaders.

**Comment by ChurchOrganist** [comment]
Would it help to send you a mod list?

Would the hidden in-game loaders cause this??

We're running a Pyanodon base atm in which we are making extensive use of Deadlock's version of these due to stack sizes.

We're also using your Bulk Rail Loaders/Unloaders but I don't see why that would have any effect.

**Comment by mspielberg** [comment]
A mod list might help, but I'll probably just add a workaround and perhaps a log message that will help you and other server owners determine which is the problematic mod. I told Mylon about the specific problem with Bluebuild many months ago, but he seems to have dropped out of Factorio modding recently. Maybe he'll be back for 0.17, or maybe I'll end up writing my own version of Bluebuild.

Can you elaborate on the "stack size" issues and why that's making Deadlock's loaders preferable for your players?

**Comment by mspielberg** [comment]
Should be fixed in 1.5.23
