### ISSUE TITLE
Server crashed - blueprints

### ISSUE THREAD

**Issue by Furius-Starfall** [mspielberg/factorio-miniloader#16]
Something with blueprints. This Error appear when player want create a blueprint. Another error is with placing blueprint.

Error while running event miniloader::on_player_setup_blueprint (ID 68)
LuaPlayer doesn't contain key blueprint_to_setup.
stack traceback:
	__miniloader__/control.lua:229: in function 'handler'
	__miniloader__/lualib/event.lua:15: in function <__miniloader__/lualib/event.lua:13>

**Comment by mspielberg** [comment]
You need to update your server to the version 0.16.13 or later of Factorio, preferably the latest stable version 0.16.51.
