### ISSUE TITLE
Miniloaders on circuit networks act upon their own output signals.

### ISSUE THREAD

**Issue by computer-whisperer** [mspielberg/factorio-miniloader#18]
Example: https://youtu.be/laflsg7HNdY

Whenever a miniloader is configured to both output a signal and respond to a signal, the outgoing signal can trigger the minloader again. This is probably due to having two inserters in the one block (one triggers the other).

**Comment by mspielberg** [comment]
Your analysis is correct. I’m unsure of a practical way to solve this however.
