### ISSUE TITLE
Loader Snapping

### ISSUE THREAD

**Issue by 0ptera** [mspielberg/factorio-miniloader#2]
Your setting also toggles Loader Redux snapping and vica versa.
Mini Loaders snap to belts parallel to their orientation but not to belts placed in front/behind them.

**Comment by mspielberg** [comment]
I was expecting Factorio to namespace its settings by mod, but apparently it does not. Thanks for the report!

**Comment by mspielberg** [comment]
Fixed in v1.1.1.
