### ISSUE TITLE
Miniloader 1.7.9 - Filter loaders not full throughput

### ISSUE THREAD

**Issue by evandy0** [mspielberg/factorio-miniloader#26]
After upgrading my game to Miniloaders 1.7.9, none of the filter loaders are giving me full throughput.    I can fix this by deleting and replacing them... but I /really/ don't want to do that to the whole darned map.    Any idea how to fix?

In the attached save, I have deleted and replaced the loaders for the Electronic Circuit Boards and the Basic Electronic Circuit boards, but none of the rest.  Should be easy to see the issue.

**Comment by evandy0** [comment]
https://www.dropbox.com/s/f17qk2p5oy339qp/AB32%20Scale%20Crystal%20Results.zip?dl=0

**Comment by mspielberg** [comment]
I’ll take a look. There is probably a bug in one of the migration scripts for upgrading an older save to 1.7.9.

**Comment by evandy0** [comment]
Probably.  I found last night that replacing them with a higher tier loader seemed to fix the problem.

**Comment by mspielberg** [comment]
Should be fixed in 1.7.10.
