### ISSUE TITLE
Circuit connection damaged after last update

### ISSUE THREAD

**Issue by JulioColino** [mspielberg/factorio-miniloader#27]
After last update 1.7.10 I still can see the red/green cable connected but the miniloaders work as there is no cable (ignoring any condition). I have to unconnect and reconnect with a new cable every single miniloader.
Miniloaders still not give the full throughput (one side goes faster than the other side) even those that I deleted and replaced just yesterday and were working properly before this last update.

**Comment by JulioColino** [comment]
After some tests, I observed that this issue only affected to most of express miniloaders (blue). After deleting and then reconnecting red/green cables to all of them, conditions work again and no more throughput issue. No need to replace miniloaders, just the cables.

**Comment by mspielberg** [comment]
I see the bug in the migration script. Thanks for the report!
