### ISSUE TITLE
Can not pick up Turbo Miniloader with Q

### ISSUE THREAD

**Issue by evandy0** [mspielberg/factorio-miniloader#28]

**Comment by evandy0** [comment]
Current build of miniloader, with Bob's Logistics.   If I hover over an existing Turbo miniloader and hit 'Q' nothing happens.

Same is true of Turbo Filter loaders.    I do not have Ultimate MiniLoaders yet, so can not test that one.    Express and below seem to function correctly.

**Comment by mspielberg** [comment]
This should be resolved in the latest version.

**Comment by evandy0** [comment]
Confirmed; thank you.
