### ISSUE TITLE
Turbo Miniloaders operate without power

### ISSUE THREAD

**Issue by evandy0** [mspielberg/factorio-miniloader#29]
Great enhancement, but probably not intended that the Turbo loaders work just fine while blinking that they have no power.

**Comment by mspielberg** [comment]
Miniloaders faster than 60 items/s use both inserters and loaders to keep up with the belt. The inserters need power but the loaders do not, so you will see the “not connected” icon for the inserters while the loader keeps working.

**Comment by evandy0** [comment]
So it's not operating at full throughput when that happens?  Interesting....

**Comment by mspielberg** [comment]
This should be resolved in the latest version.

**Comment by evandy0** [comment]
Really?  Nifty.   I figure it was just how it was going to work.   Thank you for all the quick resolutions!

**Comment by mspielberg** [comment]
A fix in 0.17.50 made it possible for inserters alone to do the job, so miniloaders no longer have the split between inserters and loaders.
