### ISSUE TITLE
Asking permission to adapt miniloader for use in my mod

### ISSUE THREAD

**Issue by raiguard** [mspielberg/factorio-miniloader#30]
Hello. I am creating [Infinity Mode](https://github.com/raiguard/InfinityMode), which is aimed at being a modernized rewrite of the classic Creative Mode mod. One of the annoyances with Creative Mode that I am trying to solve is performance, and I have come upon one of the bigger drains of performance in Creative Mode: Matter sources.

Each Matter source has an on_tick() event that consumes 0.05ms each! This, in comparison with miniloaders, which consume 0.00ms. It's obvious why I am wanting to use miniloaders for the mod.

My idea is to modify the miniloader to reposition the inserter pickup/dropoff point to somewhere within the entity. Then, I will use control scripting to place an invisible infinity chest at that location to act as an item source / void. I will create a custom GUI for my variant of the miniloader that will allow one to choose which item is dropped onto each side of the belt, identical to Creative Mode's matter source.

I am making this issue to ask your permission to use your code. I know the license doesn't really require me to, but it would feel wrong to just take it without asking. I will, of course, credit you, and I will do my best to make sure that my implementation doesn't affect your mod in any way.

Thanks in advance!

**Comment by mspielberg** [comment]
Sounds great! There’s been a long-standing request for filter miniloaders to be able to have separate filters per-lane. The sticking point has been time to implement, particularly the UI. For your purposes you’ll be building just such a UI, and I hope we’ll be able to use it for a future Miniloaders release as well.

Do you intend to use a single infinity chest as the source for the two different items, and then use filter inserters to put them on the belt?

**Comment by raiguard** [comment]
Yeah, that's basically what I had in mind. It's going to take me a while to sufficiently learn how the miniloaders are set up and work before I can modify them.

I'm not sure if it would be better for me to try to hack the backend together, or to wait until you have time to do a proper implementation of per-side filtering. My only issue is I don't know how it would work with the circuit network...

As for the UI, don't worry about it, I can do that. So long as I have a backend that works I can make a GUI for it. Here's a sample:

![image](https://user-images.githubusercontent.com/3515394/60764621-596f4800-a04a-11e9-914c-a032fee91e47.png)

Thanks again!

**Comment by mspielberg** [comment]
My plan is that it wouldn't work with the circuit network: trying to set filters via circuit network would immediately overwrite any current side-specific settings. Feel free to start hacking, and/or ask for guidance on Discord. I'm unlikely to get to it anytime soon.

**Comment by raiguard** [comment]
That sounds reasonable, I don't need the circuit network to work for my usecase anyway. I'll let you know when I inevitably need help! :)

**Comment by raiguard** [comment]
Hmm, so this has become a huge clustertruck of a thing. I thought I could simply copy the code and simplify it down to one entity, then start hacking it to make it work with per-side filtering. But I completely neglected to realize that you need to create a special loader for every belt type.

I have two tentative plans right now:
1. Fork this repository, implement per-side filtering, add this mod as a dependency of mine, and figure out how to create a new miniloader based on data from this mod
2. Completely forget about the loader part, and just create an insanely fast pair of inserters that go into an invisible infinity chest
3. Just copy Creative Mode's method and try to optimize it

I'm going to attempt to do the first option, but if it proves to be taking too long, I will have to resort to the second or the third. I only have 66 days to complete my mod, after which I will be gone for two years to be a missionary for my religion.

**Comment by raiguard** [comment]
Do you wish the per-side filtering to be a separate entity, or for it to be an option in the GUI?

**Comment by raiguard** [comment]
Is the pickup position the same for both sides on purpose? Would it mess up the timings if I separated the pickup positions to be exactly opposite from the drop positions?

**Comment by mspielberg** [comment]
The loader is only needed to handle the case where a belt turns 90 degrees as soon as it comes out of a Miniloader. Otherwise the items will all end up on the near side of the belt. Creative mode doesn’t have this issue because it puts items in the proper belt lane directly, not by position, but the whole point of your project is to avoid the scripting to do the direct manipulation.

It would probably be more work to get all the rotation cases working right than it would be to get the loaders right.

It’s unlikely you’ll be able to optimize creative mode’s technique too much. It’s just that expensive to put items onto belts one at a time with Lua script. Compare for example Loaders Redux when unloading cargo wagons, Factorissimo2 belt connections, or the old Hacked Splitters mod. Each one is known for high UPS costs for this very reason.

You may have noticed by now that when selecting a pickup entity, inserters just check the tile that the pickup position lands on. You won’t be able to reliably select two different infinity chests just by tweaking pickup position and chest position. You’ll likely need a single infinity chest with filters on the inserters instead. Do you have a different reason for wanting to change the pickup positions?

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/61188559-1c084d00-a63e-11e9-90f1-a7aa07e5e132.png)
I think I'm doing just fine with adding support for per-side filtering :D The actual functionality works, now I need to make a GUI for it!

My reasoning for wanting to move the pickup position is specifically for input loaders with per-side filtering. As it is now, each inserter will pick up from either side of the belt. This would conflict with the output loader behavior, which allows for per-side filtering.

**Comment by raiguard** [comment]
![perside miniloaders](https://user-images.githubusercontent.com/3515394/61188656-c339b400-a63f-11e9-814c-dda76c203feb.gif)
Weeeeeeeee!

**Comment by mspielberg** [comment]
Unfortunately inserters will always pick up from either side of the belt, although they prefer one lane over the other based on position.

Vanilla loaders don’t allow filtering when in “input” (belt->chest) mode, so I wouldn’t worry about it.

**Comment by raiguard** [comment]
Well that's a shame, oh well. Turns out creative mode's matter void only has one filter as well, so no functionality is actually lost.
