### ISSUE TITLE
inserter configuration GUI no display

### ISSUE THREAD

**Issue by DoubleHYH** [mspielberg/factorio-miniloader#35]
![20191220205341_1](https://user-images.githubusercontent.com/21342563/71256531-f8270100-236b-11ea-8ce9-0a36bb156850.jpg)
↑↑↑ this screenshots is my game. and this is my mods list
+ Aircraft
+ AutoDeconstruct
+ BigBags
+ Big_Brother
+ bobinserters
+ Bottleneck
+ clock
+ ElectricTrain
+ even-distribution
+ Factorissimo2
+ LoaderRedux
+ miniloader
+ misc_mod_trans
+ OmegaDrill
+ OpteraLib
+ Portals
+ pycoalprocessing
+ pyfusionenergy
+ pyhightech
+ pyindustry
+ pypetroleumhandling
+ pyrawores
+ railloader
+ RecExplo
+ Squeak Through
+ stdlib
+ Todo-List
+ Warehousing
+ WaterWell
but when i update any mod or add any mod,the game will going to be like this ↓↓↓
![20191220205520_1](https://user-images.githubusercontent.com/21342563/71257515-db3ffd00-236e-11ea-9bfd-c59207e8c02d.jpg)

pay attention to the left upper corner. i need the GUI and a lot of miniloader can not work.
how i can fix it? 
the save file size is 16.5MB,if you need ,how can post to you?
or what can i do for fix that

**Comment by mspielberg** [comment]
You cannot use Bob's Adjustable Inserters with Miniloaders. This is intentional.
