### ISSUE TITLE
[BUG] Unable to load when Bob's Logistics is present

### ISSUE THREAD

**Issue by SonOfTheStars** [mspielberg/factorio-miniloader#37]
When attempting to load version 1.10.1, while having Bob's Logistics enabled, a nil-value error pops up during loading.
See entities.lua Line 27
![image](https://user-images.githubusercontent.com/3910862/75607949-92898a80-5afb-11ea-85a9-b28d9d241a24.png)

Game Version: 0.18.9
Modlist and Configs:[mods.zip](https://github.com/mspielberg/factorio-miniloader/files/4270309/mods.zip)

**Comment by mspielberg** [comment]
Fixed in v1.10.2.
