### ISSUE TITLE
1.10.4 crashes all versions of 0.18 

### ISSUE THREAD

**Issue by 0ptera** [mspielberg/factorio-miniloader#38]
One of my saves crashes hard using miniloader 1.10.4.
https://forums.factorio.com/viewtopic.php?p=484484#p484484

Any save made with 1.10.4 of this map, be it a straight port from 0.17.59 or from 0.18.12 with miniloader 1.10.3, reliably crashes when loading.

**Comment by mspielberg** [comment]
I'm making miniloaders have a collision mask again. There wasn't any reason they didn't have one to begin with.
