### ISSUE TITLE
Crash when mining a particular mini-loader

### ISSUE THREAD

**Issue by evandy0** [mspielberg/factorio-miniloader#39]
In attached save, mine the miniloader the player is standing next to (by robot or by hand) - crash

Mine any of the other ones, no problem.

HELP!  This is a seablock save, so many mods.
[SB_18.9.1.zip](https://github.com/mspielberg/factorio-miniloader/files/4388945/SB_18.9.1.zip)

**Comment by evandy0** [comment]
Update: Placing waterfill on it is interesting ... the entity remains behind floating on the water.   Shooting it to destroy it allows me to remove the ghost so at least my game isn't wrecked.

**Comment by mspielberg** [comment]
By some odd twist of magic, this particular miniloader has 275 items on one side of the (half-tile long) belt, and 295 items on the other, for a total of 570 items. Apparently while Factorio can tell me there are that many items in a lane of a belt, actually trying to access the ones beyond the 256th &mdash; in this case so they can be returned to the player &mdash; causes things to crash.

There aren't too many options here, and I'm not sure how that belt tile got that way, but I'll change miniloader to just ignore any items past the first 256 items, and they'll be destroyed.

EDIT: Amusingly, if you walk over the miniloader and just hit 'F' to empty the belt, you can mine it just fine.

**Comment by evandy0** [comment]
Well, I'm glad there is another workaround.... I don't even understand how there can be that many items on the belt?  There is something very very wrong there, but I like the protection code.

Thank you for running this to ground.
