### ISSUE TITLE
Cannot transfer items directly between containers

### ISSUE THREAD

**Issue by HactarCE** [mspielberg/factorio-miniloader#4]
If these loaders really are just (pairs of) invisible inserters, they should be able to transfer from chest to chest just as well as belt to chest. Maybe I'm just misunderstanding how loaders work, in general?

**Comment by mspielberg** [comment]
The inserters interact with two tiles, the tile of the mini loader, meaning the belt on the same tile, and the tile adjacent to the "chest" side of the miniloader. They do not interact with the belt on the tile adjacent to the loader's "belt" side. If they did, it could lead to strange cases where the adjacent belt is pointed away from the loader, but items are still being removed from the belt anyway.
