### ISSUE TITLE
Integrating with factorio-mods-localization on crowdin

### ISSUE THREAD

**Issue by metalbass** [mspielberg/factorio-miniloader#45]
In order to translate this mod more comfortably, I forked the repo and integrated with https://crowdin.com/project/factorio-mods-localization with a few clicks.

Any translations that are made from the page will go into my fork of the repo without any additional interaction (you can see that it also auto-commits the changes [here](https://github.com/metalbass/factorio-miniloader/commit/c238d4eeb6314056af4ab072a2e348adfef03f03)).

Ideally they should get into the original repo, not a fork, so that they are automatically added to the latest version of the mod.
I don't have any issue about making PRs to your repo to add new localization, but I think the original repo should be the one linked.

What do you think? :)

**Comment by dima74** [comment]
Just in case here is link to `factorio-mods-localization` repository with detailed description: https://github.com/dima74/factorio-mods-localization

**Comment by mspielberg** [comment]
That's for the pointer! I was not aware of this project, but I've added the integration now.

**Comment by dima74** [comment]
@mspielberg thanks for trying `factorio-mods-localization`! I noticied that you installed github app for all your repositories, and unfortunately it is not supported now. Could you please reinstall github app and manually select repositories? 

![image](https://user-images.githubusercontent.com/6505554/81478968-081b8080-923a-11ea-80fa-c45c1c279aa1.png)
