### ISSUE TITLE
1.15.0 revert back to 1.14.x not possible 

### ISSUE THREAD

**Issue by Aringarosa** [mspielberg/factorio-miniloader#65]
Hey mspielberg,

It is not possible to revert to 1.14.8 if 15.0.0 filter loaders have been placed. Every time I select something from the hot bar I get this error.

![image](https://user-images.githubusercontent.com/5900536/152640140-6c044416-c2ae-4d27-8383-2b27e43804a1.png)

I've also tried downgrading the versions, to no avail. Now I guess I'm waiting for your fix for 1.15.0

Greetings Ringo

**Comment by mspielberg** [comment]
v1.14.9 should now have fixed this. Sorry!
