### ISSUE TITLE
1.15.1 - Bug when picking up wired inserters

### ISSUE THREAD

**Issue by notacompletemoron** [mspielberg/factorio-miniloader#67]
I wire them for every train station. So, picking up with both player and bots hurts.

The mod Miniloader (1.15.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event miniloader::Custom event (ID 260)
miniloader/circuit.lua:51: attempt to index local 'target' (a nil value)
stack traceback:
miniloader/circuit.lua:51: in function 'copy_inserter_behavior'
miniloader/circuit.lua:78: in function 'sync_behavior'
miniloader/circuit.lua:170: in function 'sync_partner_connections'
miniloader/circuit.lua:247: in function 'handler'
miniloader/lualib/event.lua:15: in function <miniloader/lualib/event.lua:13>
[C]: in function 'raise_event'
miniloader/lualib/onwireplaced.lua:104: in function 'raise_on_wire_removed'
miniloader/lualib/onwireplaced.lua:220: in function 'handler'
miniloader/lualib/event.lua:15: in function <miniloader/lualib/event.lua:13>
stack traceback:
[C]: in function 'raise_event'
miniloader/lualib/onwireplaced.lua:104: in function 'raise_on_wire_removed'
miniloader/lualib/onwireplaced.lua:220: in function 'handler'
miniloader/lualib/event.lua:15: in function <miniloader/lualib/event.lua:13>

**Comment by mspielberg** [comment]
Fixed in v1.15.2.
