### ISSUE TITLE
1.15.2 - Crash when placing loaders

### ISSUE THREAD

**Issue by notacompletemoron** [mspielberg/factorio-miniloader#68]
The mod Miniloader (1.15.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event miniloader::on_robot_built_entity (ID 14)
miniloader/lualib/util.lua:404: bad argument #1 of 2 to 'pairs' (table expected, got nil)
stack traceback:
[C]: in function 'pairs'
miniloader/lualib/util.lua:404: in function 'apply_settings'
miniloader/lualib/miniloader.lua:153: in function <miniloader/lualib/miniloader.lua:137>
(...tail calls...)
miniloader/control.lua:111: in function 'handler'
miniloader/lualib/event.lua:15: in function <miniloader/lualib/event.lua:13>

**Comment by mspielberg** [comment]
Can you try v1.15.3?

**Comment by notacompletemoron** [comment]
Works now! Thank you!
