### ISSUE TITLE
Factorio 2.0 compatibility?

### ISSUE THREAD

**Issue by AwesomeCronk** [mspielberg/factorio-miniloader#78]
Are you intending to update miniloaders to Factorio 2.0? I am interested in porting it if needed, but I would rather not invest the time if you're already halfway done.

**Comment by bplein** [comment]
I am also interested. I am trying to port it myself but I am new to Factorio modding as well as very novice in Lua. Just let us know @mspielberg if you are still interested in maintaining this or if we should fork it and start working on it. Thank you!

**Comment by AwesomeCronk** [comment]
> I am also interested. I am trying to port it myself but I am new to Factorio modding as well as very novice in Lua. Just let us know @mspielberg if you are still interested in maintaining this or if we should fork it and start working on it. Thank you!

I have found and tested loaders-modernized by kryojenik, which uses the builtin loader entity and by default the miniloader graphics. It can even port old miniloader builds. It's almost 100% compatible.

**Comment by bplein** [comment]
Yes, there's a manual migration path that I'll need to do for my headless linux public servers (move the save to my desktop, migrate it by opening it up, and then sending it back to the server and testing). But I only have 3 active servers to migrate and possibly some old saves.
