### ISSUE TITLE
Miniloaders can be placed "backwards"

### ISSUE THREAD

**Issue by CodeW0lf** [mspielberg/factorio-miniloader#8]
Miniloaders can be placed "backwards" on a belt which still allows items to flow through but will not compress a belt. When placing the miniloader you have to ensure that you face the yellow arrow on the entity towards the incoming items.

![miniloaders_backwards](https://user-images.githubusercontent.com/602465/37081458-5dc30490-219e-11e8-9146-a7005c06820a.png)

**Comment by mspielberg** [comment]
I believe this should be fixed in the current version of Miniloader, by slightly speeding up the inserters.
